name: Build Android APK

on:
  push:
    branches: [ main, master, all_flutter ]
  pull_request:
    branches: [ main, master, all_flutter ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Get dependencies
      working-directory: ./front
      run: flutter pub get
      
    - name: Build APK
      working-directory: ./front
      run: flutter build apk --release --split-per-abi
      
    - name: Upload APK (ARM64)
      uses: actions/upload-artifact@v4
      with:
        name: app-arm64-v8a-release
        path: front/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        
    - name: Upload APK (ARMv7)
      uses: actions/upload-artifact@v4
      with:
        name: app-armeabi-v7a-release
        path: front/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        
    - name: Upload APK (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: app-x86_64-release
        path: front/build/app/outputs/flutter-apk/app-x86_64-release.apk
